拓展onOK参数
rsuite/interactions pull request #10
Opened 2020-09-21 06:40 UTC by begoat

close #9 
1. 增加react-hooks 的 eslint插件，固定了版本号2.5.1. 因为更高的版本的警告好像有一点不准确
2. 支持覆盖onOk 函数，如果是返回是promise的话，会显示loading，在promise的最后把loading关闭

2020-09-21 10:11 UTC, SevenOutman requested changes
`await alert(...)` 返回了 `true`，应当是 void 才对。

2020-09-21 11:08 UTC, SevenOutman requested changes

2020-09-21 11:08 UTC, SevenOutman commented on src/InteractionModal.js
> +  resolveFn,
Modal 不需要添加新的 props，只需要支持 onOk 返回值为 Promise 时先 loading 再关闭就可以了。resolve 的部分应该在 alert 里包装。

类似这样：

```
alert(config) {
  <Modal
    onOk={async () => {
      await config.onOk()
      resolve()
    }}
  />
}
```

2020-09-22 02:52 UTC, begoat commented on src/InteractionModal.js
> +  resolveFn,
已修改。

当时的考虑是：如果resolve 的部分放在InteractionModal里面，就不需要在alert、confirm、prompt三个组件都去处理了。

不过像你上面这么写也比较简洁，而且这个组件promise resolve的部分确实应该在外面处理。

2020-09-22 03:29 UTC, SevenOutman requested changes

2020-09-22 03:29 UTC, SevenOutman commented on src/confirm.js
> +            result = await modalConfig.onOk();
`onOk` 应当可以接收到 `confirm` 的结果

2020-09-22 03:29 UTC, SevenOutman commented on src/InteractionModal.js
> +        <Button loading={submitLoading} onClick={handleOk} appearance="primary">
需要考虑
- 是否在 loading 时设置 `disabled`？（重复点击按钮的情况）
- loading 是是否允许点击取消按钮？

2020-09-22 04:00 UTC, begoat commented on src/InteractionModal.js
> +        <Button loading={submitLoading} onClick={handleOk} appearance="primary">
1. rsuite默认loading之后就不能再点击了
2. 如果在loading时`不可以`点取消，那么万一这个请求很长很长，那用户就一直在这个界面了，在这种情况下感觉不太合理；如果`可以点击`取消，那得交给开发者自己处理请求取消的情况，你觉得呢？

2020-09-22 06:02 UTC, SevenOutman commented on src/InteractionModal.js
> +        <Button loading={submitLoading} onClick={handleOk} appearance="primary">
我感觉允许点击取消有一个点不太合理：`onOk` 返回 Promise 的场景通常是一些操作的确认，在这种场景下，当请求发出后，“取消”操作给人的直观感受是“取消当前操作”。可这时很可能请求已经被服务端处理，操作的结果已经形成，“取消”并不能撤回原本的操作。所以我觉得还是禁止取消更合适，不容易造成理解偏差。

如果后续真的有开发者需要支持取消异步操作的场景，可以考虑添加 `onCancel` 选项，通过此选项是否存在判断是否允许点击取消。目前还没有实际的取消异步操作的需求出现，提前构思可能会存在意料之外的漏洞。

2020-09-22 06:10 UTC, begoat commented on src/confirm.js
> +            result = await modalConfig.onOk();
这一点不太理解，onOk就是 整个弹窗点了确定按钮后的 操作，

confirm整个弹窗的结果（点了是还是否）的话，通过confirm这个函数的promise返回值可以拿到

2020-09-22 06:21 UTC, begoat commented on src/InteractionModal.js
> +        <Button loading={submitLoading} onClick={handleOk} appearance="primary">
对哦。我们现在可以`加一个参数` 来控制是否 允许在loading的时候取消的

2020-09-22 07:57 UTC, SevenOutman commented on src/confirm.js
> +            result = await modalConfig.onOk();
嗯对，考虑错了

2020-09-22 09:49 UTC, SevenOutman requested changes
我

2020-09-22 09:49 UTC, SevenOutman commented on src/InteractionModal.js
> +  canCancelOnLoading = false
如果提供允许取消的选项，应当一并提供设置取消操作逻辑的选项如 `onCancel`。

2020-09-22 10:21 UTC, begoat commented on src/InteractionModal.js
> +  canCancelOnLoading = false
提供了允许取消的选项是想交给开发者去处理，我们提供默认值，不过没到位没有支持你提到的onCancel回掉函数。

现已添加，允许开发者去在onCancel的时候根据函数的参数去判断是否数据正在请求，去做一些“取消”操作。比如axios在这种情况下的话可以直接通过调用函数时提供的mutex去cancel。

2020-09-23 04:57 UTC, SevenOutman requested changes

2020-09-23 04:57 UTC, SevenOutman commented on index.d.ts
> +  canCancelOnLoading?: boolean;
`alert` 应该不需要 `canCancelOnLoading` 选项

2020-09-23 04:57 UTC, SevenOutman commented on index.d.ts
> +  onCancel?: ((isSubmitLoading?: boolean) => void) | ((isSubmitLoading?: boolean) => Promise<any>);
这里应该不需要关心 `onCancel` 的返回值，类型返回 any 就可以

2020-09-23 06:51 UTC, begoat commented on index.d.ts
> +  canCancelOnLoading?: boolean;
嗯，是的

2020-09-23 06:51 UTC, begoat commented on index.d.ts
> +  onCancel?: ((isSubmitLoading?: boolean) => void) | ((isSubmitLoading?: boolean) => Promise<any>);
嗯 是的

2020-09-23 07:30 UTC, SevenOutman approved these changes

2020-09-23 07:31 UTC, merged

2020-09-23 07:34 UTC, begoat commented
Finally 🤣
THX